name: Software-Engineering-Tools-Homework

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      
      - name: Install Dependencies
        run: |
          pip install dvc pandas numpy pytest
      
      - name: Setup DVC
        run: |
          pip install dvc
          if [ ! -d .dvc ]; then
            dvc init --no-scm
            dvc remote add -d localremote /tmp/dvc-storage
          fi
      
      - name: Run Data Quality Checks
        run: |
          python tests/test_data_checks.py
